baseurl = "https://blog.haivq.com/"
author = "Aperture"
languageCode = "en-us"
title = "Blog của Aperture"
theme = "terminal"
paginate = 5
enableRobotsTXT = true

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "orange"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 3

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  enableGitInfo = false
  showLastUpdated = false
  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  updatedDatePrefix = "Cập nhật"

  # set all headings to their default size (depending on browser settings)
  # it's set to `true` by default
  # oneHeadingSize = false

[languages]
  [languages.en.params]
    languageName = "English"
    title = "Góc của Aperture"
    subtitle = "Nơi ghi chép kinh nghiệm (đôi khi là cả suy nghĩ) của tôi"
    owner = "Aperture Prometheus"
    keywords = "devops,coding,resume,thoughts"
    copyright = "Aperture Prometheus"
    menuMore = "Xem thêm"
    readMore = "Đọc tiếp"
    newerPosts = "Bài mới hơn"
    olderPosts = "Bài cũ hơn"
    readOtherPosts = "Xem tiếp"
    missingContentMessage = "Không tìm thấy trang..."
    missingBackButtonLabel = "Về trang chủ"
    minuteReadingTime = "phút đọc"

    [languages.en.params.logo]
      logoText = "Góc của Aperture"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "Thông tin"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "thoughts"
        name = "Suy nghĩ của tôi"
        url = "https://thoughts.haivq.com"
      [[languages.en.menu.main]]
        identifier = "rss"
        name = "RSS"
        url = "/index.xml"

[markup.goldmark.renderer]
  unsafe = true